influxdb:
  image: influxdb:1.7.10-alpine
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'influxdb.env'

db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_DATABASE: smec
    MYSQL_USER: user
    MYSQL_PASSWORD: password
