apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/tmp/smec/mysql-pv-0"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv-0
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/tmp/smec/influx-pv-0"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
